receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      cpu:
      memory:
  otlp:
    protocols:
      http:
        endpoint: otel-collector:5555

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  prometheus:
    endpoint: otel-collector:6666
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki:3100/otlp
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, logging]
  telemetry:
    logs:
      level: debug
