global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'otel-collector:6666' ]
  - job_name: 'tempo'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'tempo:3200' ]
