server:
  http_listen_port: 3200
  log_level: debug

distributor:
  ring:
    kvstore:
      store: "inmemory"
  receivers:
    jaeger:
      protocols:
        thrift_http:
        grpc:
        thrift_binary:
        thrift_compact:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    compaction_window: 1h
    max_block_bytes: 100_000_000
    block_retention: 1h
    compacted_block_retention: 24h

# Metrics-generator configuration block
metrics_generator:
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  registry:
    collection_interval: 15s
    external_labels:
      source: tempo
      cluster: docker-compose
  traces_storage:
    path: /tmp/tempo/generator/traces
  # Processor-specific configuration
  processor:
    span_metrics:
      enable_target_info: true
    service_graphs:
      wait: 10
      max_items: 10000
      workers: 10
      histogram_buckets: [ 0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8 ]
      enable_messaging_system_latency_histogram: true
storage:
  trace:
    backend: local
    block:
      bloom_filter_false_positive: .05
      v2_encoding: zstd
    wal:
      path: /tmp/tempo/wal
      v2_encoding: snappy
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
  #per_tenant_override_config: /etc/tempo/overrides.yaml
